version: '2'
services:
  api:
    build: ./api-dotnet/bin/Debug/netcoreapp1.0/publish
    image: "${REPO}container-lab-api"
    ports:
      - 5000:5000
    networks:
      - lab
  web:
    build: ./web-node

    image: "${REPO}container-lab-web"
    ports:
      - 8888:3000
    networks:
      - lab
    environment:
      - APIURL=api
    depends_on:
      - api
networks:
  lab:
    driver: bridge
