version: '2'
services:
  api:
    build: ./api-dotnet/bin/Debug/netcoreapp1.0/publish
    image: "${REPO}container-lab-api"
    ports:
      - 5000:5000
    networks:
      - lab
  web:
    build: ./web-node

    image: "${REPO}container-lab-web"
    ports:
      - 80:3000
    networks:
      - lab
    environment:
      - APIURL=api
    depends_on:
      - api
# Labels used to configure Docker Data Center load Balancers
    labels:
      - "interlock.context_root=/container-lab-web"
      - "interlock.context_root_rewrite=true"
# Driver default will be based on engine
networks:
  lab:
