apiVersion: v1
kind: Service
metadata:
  name: container-lab-web
  labels:
    name: container-lab-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: container-lab-web